version: '3.5'
services:
  postgres:
    container_name: clair_postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./volumes/postgres:/var/lib/postgresql
    networks:
      docker_scan: {}

  clair:
    container_name: clair_clair
    image: quay.io/coreos/clair:latest
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    links:
      - postgres
    volumes:
      - /tmp:/tmp
      - ./clair_config:/config
    command: [-config, /config/config.yaml]
    networks:
      docker_scan: {}

networks:
  docker_scan:
    driver: bridge
    name: docker_scan
